/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AluminiumDoorInstallationMumbaiRouteImport } from './routes/aluminium-door-installation-mumbai'
import { Route as AluminiumKitchenCupboardMumbaiRouteImport } from './routes/aluminium-kitchen-cupboard-mumbai'
import { Route as AluminiumPartitionInstallationMumbaiRouteImport } from './routes/aluminium-partition-installation-mumbai'
import { Route as AluminiumPartitionRepairMumbaiRouteImport } from './routes/aluminium-partition-repair-mumbai'
import { Route as AluminiumWindowRepairPowaiRouteImport } from './routes/aluminium-window-repair-powai'
import { Route as BathroomWindowMumbaiRouteImport } from './routes/bathroom-window-mumbai'
import { Route as CustomWindowModificationMumbaiRouteImport } from './routes/custom-window-modification-mumbai'
import { Route as DomalWindowRepairMumbaiRouteImport } from './routes/domal-window-repair-mumbai'
import { Route as FrenchWindowsMumbaiRouteImport } from './routes/french-windows-mumbai'
import { Route as GlassBalconyRailingMumbaiRouteImport } from './routes/glass-balcony-railing-mumbai'
import { Route as GlassPartitionMumbaiRouteImport } from './routes/glass-partition-mumbai'
import { Route as GlassShopPowaiRouteImport } from './routes/glass-shop-powai'
import { Route as InvisibleGrillsMumbaiRouteImport } from './routes/invisible-grills-mumbai'
import { Route as MosquitoNetSlidingWindowMumbaiRouteImport } from './routes/mosquito-net-sliding-window-mumbai'
import { Route as NewWindowInstallationMumbaiRouteImport } from './routes/new-window-installation-mumbai'
import { Route as PigeonNetInstallationMumbaiRouteImport } from './routes/pigeon-net-installation-mumbai'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RubberGasketSealingMumbaiRouteImport } from './routes/rubber-gasket-sealing-mumbai'
import { Route as SafetyNetsInstallationMumbaiRouteImport } from './routes/safety-nets-installation-mumbai'
import { Route as SlidingDoorRepairPowaiRouteImport } from './routes/sliding-door-repair-powai'
import { Route as SlidingWindowRepairPowaiRouteImport } from './routes/sliding-window-repair-powai'
import { Route as SoundproofWindowUpgradesMumbaiRouteImport } from './routes/soundproof-window-upgrades-mumbai'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WindowAlignmentMaintenanceMumbaiRouteImport } from './routes/window-alignment-maintenance-mumbai'
import { Route as WindowGlassReplacementPowaiRouteImport } from './routes/window-glass-replacement-powai'
import { Route as WindowLockRepairPowaiRouteImport } from './routes/window-lock-repair-powai'
import { Route as WindowRepairAndheriWestEastRouteImport } from './routes/window-repair-andheri-west-east'
import { Route as WindowRepairBandraJuhuRouteImport } from './routes/window-repair-bandra-juhu'
import { Route as WindowRepairBkcKurlaRouteImport } from './routes/window-repair-bkc-kurla'
import { Route as WindowRepairChandivaliSakiViharRouteImport } from './routes/window-repair-chandivali-saki-vihar'
import { Route as WindowRepairChemburSionRouteImport } from './routes/window-repair-chembur-sion'
import { Route as WindowRepairColabaFortRouteImport } from './routes/window-repair-colaba-fort'
import { Route as WindowRepairDadarMahimRouteImport } from './routes/window-repair-dadar-mahim'
import { Route as WindowRepairGoregaonMaladRouteImport } from './routes/window-repair-goregaon-malad'
import { Route as WindowRepairKandivaliBorivaliRouteImport } from './routes/window-repair-kandivali-borivali'
import { Route as WindowRepairKanjurmargBhandupRouteImport } from './routes/window-repair-kanjurmarg-bhandup'
import { Route as WindowRepairMulundNahurRouteImport } from './routes/window-repair-mulund-nahur'
import { Route as WindowRepairMumbaiRouteImport } from './routes/window-repair-mumbai'
import { Route as WindowRepairPowaiHiranandaniRouteImport } from './routes/window-repair-powai-hiranandani'
import { Route as WindowRepairSantacruzKharRouteImport } from './routes/window-repair-santacruz-khar'
import { Route as WindowRepairSouthMumbaiCuffeParadeRouteImport } from './routes/window-repair-south-mumbai-cuffe-parade'
import { Route as WindowRepairThaneRouteImport } from './routes/window-repair-thane'
import { Route as WindowRepairVikhroliGhatkoparRouteImport } from './routes/window-repair-vikhroli-ghatkopar'
import { Route as WindowRepairWorliPrabhadeviRouteImport } from './routes/window-repair-worli-prabhadevi'
import { Route as WindowRollerRepairPowaiRouteImport } from './routes/window-roller-repair-powai'
import { Route as WindowTrackRepairPowaiRouteImport } from './routes/window-track-repair-powai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AluminiumDoorInstallationMumbaiRoute =
  AluminiumDoorInstallationMumbaiRouteImport.update({
    id: '/aluminium-door-installation-mumbai',
    path: '/aluminium-door-installation-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const AluminiumKitchenCupboardMumbaiRoute =
  AluminiumKitchenCupboardMumbaiRouteImport.update({
    id: '/aluminium-kitchen-cupboard-mumbai',
    path: '/aluminium-kitchen-cupboard-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const AluminiumPartitionInstallationMumbaiRoute =
  AluminiumPartitionInstallationMumbaiRouteImport.update({
    id: '/aluminium-partition-installation-mumbai',
    path: '/aluminium-partition-installation-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const AluminiumPartitionRepairMumbaiRoute =
  AluminiumPartitionRepairMumbaiRouteImport.update({
    id: '/aluminium-partition-repair-mumbai',
    path: '/aluminium-partition-repair-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const AluminiumWindowRepairPowaiRoute =
  AluminiumWindowRepairPowaiRouteImport.update({
    id: '/aluminium-window-repair-powai',
    path: '/aluminium-window-repair-powai',
    getParentRoute: () => rootRouteImport,
  } as any)
const BathroomWindowMumbaiRoute = BathroomWindowMumbaiRouteImport.update({
  id: '/bathroom-window-mumbai',
  path: '/bathroom-window-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWindowModificationMumbaiRoute =
  CustomWindowModificationMumbaiRouteImport.update({
    id: '/custom-window-modification-mumbai',
    path: '/custom-window-modification-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const DomalWindowRepairMumbaiRoute = DomalWindowRepairMumbaiRouteImport.update({
  id: '/domal-window-repair-mumbai',
  path: '/domal-window-repair-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const FrenchWindowsMumbaiRoute = FrenchWindowsMumbaiRouteImport.update({
  id: '/french-windows-mumbai',
  path: '/french-windows-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassBalconyRailingMumbaiRoute =
  GlassBalconyRailingMumbaiRouteImport.update({
    id: '/glass-balcony-railing-mumbai',
    path: '/glass-balcony-railing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const GlassPartitionMumbaiRoute = GlassPartitionMumbaiRouteImport.update({
  id: '/glass-partition-mumbai',
  path: '/glass-partition-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassShopPowaiRoute = GlassShopPowaiRouteImport.update({
  id: '/glass-shop-powai',
  path: '/glass-shop-powai',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisibleGrillsMumbaiRoute = InvisibleGrillsMumbaiRouteImport.update({
  id: '/invisible-grills-mumbai',
  path: '/invisible-grills-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const MosquitoNetSlidingWindowMumbaiRoute =
  MosquitoNetSlidingWindowMumbaiRouteImport.update({
    id: '/mosquito-net-sliding-window-mumbai',
    path: '/mosquito-net-sliding-window-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewWindowInstallationMumbaiRoute =
  NewWindowInstallationMumbaiRouteImport.update({
    id: '/new-window-installation-mumbai',
    path: '/new-window-installation-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PigeonNetInstallationMumbaiRoute =
  PigeonNetInstallationMumbaiRouteImport.update({
    id: '/pigeon-net-installation-mumbai',
    path: '/pigeon-net-installation-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RubberGasketSealingMumbaiRoute =
  RubberGasketSealingMumbaiRouteImport.update({
    id: '/rubber-gasket-sealing-mumbai',
    path: '/rubber-gasket-sealing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SafetyNetsInstallationMumbaiRoute =
  SafetyNetsInstallationMumbaiRouteImport.update({
    id: '/safety-nets-installation-mumbai',
    path: '/safety-nets-installation-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlidingDoorRepairPowaiRoute = SlidingDoorRepairPowaiRouteImport.update({
  id: '/sliding-door-repair-powai',
  path: '/sliding-door-repair-powai',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidingWindowRepairPowaiRoute =
  SlidingWindowRepairPowaiRouteImport.update({
    id: '/sliding-window-repair-powai',
    path: '/sliding-window-repair-powai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SoundproofWindowUpgradesMumbaiRoute =
  SoundproofWindowUpgradesMumbaiRouteImport.update({
    id: '/soundproof-window-upgrades-mumbai',
    path: '/soundproof-window-upgrades-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowAlignmentMaintenanceMumbaiRoute =
  WindowAlignmentMaintenanceMumbaiRouteImport.update({
    id: '/window-alignment-maintenance-mumbai',
    path: '/window-alignment-maintenance-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowGlassReplacementPowaiRoute =
  WindowGlassReplacementPowaiRouteImport.update({
    id: '/window-glass-replacement-powai',
    path: '/window-glass-replacement-powai',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowLockRepairPowaiRoute = WindowLockRepairPowaiRouteImport.update({
  id: '/window-lock-repair-powai',
  path: '/window-lock-repair-powai',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairAndheriWestEastRoute =
  WindowRepairAndheriWestEastRouteImport.update({
    id: '/window-repair-andheri-west-east',
    path: '/window-repair-andheri-west-east',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairBandraJuhuRoute = WindowRepairBandraJuhuRouteImport.update({
  id: '/window-repair-bandra-juhu',
  path: '/window-repair-bandra-juhu',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairBkcKurlaRoute = WindowRepairBkcKurlaRouteImport.update({
  id: '/window-repair-bkc-kurla',
  path: '/window-repair-bkc-kurla',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairChandivaliSakiViharRoute =
  WindowRepairChandivaliSakiViharRouteImport.update({
    id: '/window-repair-chandivali-saki-vihar',
    path: '/window-repair-chandivali-saki-vihar',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairChemburSionRoute = WindowRepairChemburSionRouteImport.update({
  id: '/window-repair-chembur-sion',
  path: '/window-repair-chembur-sion',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairColabaFortRoute = WindowRepairColabaFortRouteImport.update({
  id: '/window-repair-colaba-fort',
  path: '/window-repair-colaba-fort',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairDadarMahimRoute = WindowRepairDadarMahimRouteImport.update({
  id: '/window-repair-dadar-mahim',
  path: '/window-repair-dadar-mahim',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairGoregaonMaladRoute =
  WindowRepairGoregaonMaladRouteImport.update({
    id: '/window-repair-goregaon-malad',
    path: '/window-repair-goregaon-malad',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairKandivaliBorivaliRoute =
  WindowRepairKandivaliBorivaliRouteImport.update({
    id: '/window-repair-kandivali-borivali',
    path: '/window-repair-kandivali-borivali',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairKanjurmargBhandupRoute =
  WindowRepairKanjurmargBhandupRouteImport.update({
    id: '/window-repair-kanjurmarg-bhandup',
    path: '/window-repair-kanjurmarg-bhandup',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairMulundNahurRoute = WindowRepairMulundNahurRouteImport.update({
  id: '/window-repair-mulund-nahur',
  path: '/window-repair-mulund-nahur',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairMumbaiRoute = WindowRepairMumbaiRouteImport.update({
  id: '/window-repair-mumbai',
  path: '/window-repair-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairPowaiHiranandaniRoute =
  WindowRepairPowaiHiranandaniRouteImport.update({
    id: '/window-repair-powai-hiranandani',
    path: '/window-repair-powai-hiranandani',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairSantacruzKharRoute =
  WindowRepairSantacruzKharRouteImport.update({
    id: '/window-repair-santacruz-khar',
    path: '/window-repair-santacruz-khar',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairSouthMumbaiCuffeParadeRoute =
  WindowRepairSouthMumbaiCuffeParadeRouteImport.update({
    id: '/window-repair-south-mumbai-cuffe-parade',
    path: '/window-repair-south-mumbai-cuffe-parade',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairThaneRoute = WindowRepairThaneRouteImport.update({
  id: '/window-repair-thane',
  path: '/window-repair-thane',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowRepairVikhroliGhatkoparRoute =
  WindowRepairVikhroliGhatkoparRouteImport.update({
    id: '/window-repair-vikhroli-ghatkopar',
    path: '/window-repair-vikhroli-ghatkopar',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRepairWorliPrabhadeviRoute =
  WindowRepairWorliPrabhadeviRouteImport.update({
    id: '/window-repair-worli-prabhadevi',
    path: '/window-repair-worli-prabhadevi',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRollerRepairPowaiRoute = WindowRollerRepairPowaiRouteImport.update({
  id: '/window-roller-repair-powai',
  path: '/window-roller-repair-powai',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowTrackRepairPowaiRoute = WindowTrackRepairPowaiRouteImport.update({
  id: '/window-track-repair-powai',
  path: '/window-track-repair-powai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluminium-door-installation-mumbai': typeof AluminiumDoorInstallationMumbaiRoute
  '/aluminium-kitchen-cupboard-mumbai': typeof AluminiumKitchenCupboardMumbaiRoute
  '/aluminium-partition-installation-mumbai': typeof AluminiumPartitionInstallationMumbaiRoute
  '/aluminium-partition-repair-mumbai': typeof AluminiumPartitionRepairMumbaiRoute
  '/aluminium-window-repair-powai': typeof AluminiumWindowRepairPowaiRoute
  '/bathroom-window-mumbai': typeof BathroomWindowMumbaiRoute
  '/custom-window-modification-mumbai': typeof CustomWindowModificationMumbaiRoute
  '/domal-window-repair-mumbai': typeof DomalWindowRepairMumbaiRoute
  '/french-windows-mumbai': typeof FrenchWindowsMumbaiRoute
  '/glass-balcony-railing-mumbai': typeof GlassBalconyRailingMumbaiRoute
  '/glass-partition-mumbai': typeof GlassPartitionMumbaiRoute
  '/glass-shop-powai': typeof GlassShopPowaiRoute
  '/invisible-grills-mumbai': typeof InvisibleGrillsMumbaiRoute
  '/mosquito-net-sliding-window-mumbai': typeof MosquitoNetSlidingWindowMumbaiRoute
  '/new-window-installation-mumbai': typeof NewWindowInstallationMumbaiRoute
  '/pigeon-net-installation-mumbai': typeof PigeonNetInstallationMumbaiRoute
  '/privacy': typeof PrivacyRoute
  '/rubber-gasket-sealing-mumbai': typeof RubberGasketSealingMumbaiRoute
  '/safety-nets-installation-mumbai': typeof SafetyNetsInstallationMumbaiRoute
  '/sliding-door-repair-powai': typeof SlidingDoorRepairPowaiRoute
  '/sliding-window-repair-powai': typeof SlidingWindowRepairPowaiRoute
  '/soundproof-window-upgrades-mumbai': typeof SoundproofWindowUpgradesMumbaiRoute
  '/terms': typeof TermsRoute
  '/window-alignment-maintenance-mumbai': typeof WindowAlignmentMaintenanceMumbaiRoute
  '/window-glass-replacement-powai': typeof WindowGlassReplacementPowaiRoute
  '/window-lock-repair-powai': typeof WindowLockRepairPowaiRoute
  '/window-repair-andheri-west-east': typeof WindowRepairAndheriWestEastRoute
  '/window-repair-bandra-juhu': typeof WindowRepairBandraJuhuRoute
  '/window-repair-bkc-kurla': typeof WindowRepairBkcKurlaRoute
  '/window-repair-chandivali-saki-vihar': typeof WindowRepairChandivaliSakiViharRoute
  '/window-repair-chembur-sion': typeof WindowRepairChemburSionRoute
  '/window-repair-colaba-fort': typeof WindowRepairColabaFortRoute
  '/window-repair-dadar-mahim': typeof WindowRepairDadarMahimRoute
  '/window-repair-goregaon-malad': typeof WindowRepairGoregaonMaladRoute
  '/window-repair-kandivali-borivali': typeof WindowRepairKandivaliBorivaliRoute
  '/window-repair-kanjurmarg-bhandup': typeof WindowRepairKanjurmargBhandupRoute
  '/window-repair-mulund-nahur': typeof WindowRepairMulundNahurRoute
  '/window-repair-mumbai': typeof WindowRepairMumbaiRoute
  '/window-repair-powai-hiranandani': typeof WindowRepairPowaiHiranandaniRoute
  '/window-repair-santacruz-khar': typeof WindowRepairSantacruzKharRoute
  '/window-repair-south-mumbai-cuffe-parade': typeof WindowRepairSouthMumbaiCuffeParadeRoute
  '/window-repair-thane': typeof WindowRepairThaneRoute
  '/window-repair-vikhroli-ghatkopar': typeof WindowRepairVikhroliGhatkoparRoute
  '/window-repair-worli-prabhadevi': typeof WindowRepairWorliPrabhadeviRoute
  '/window-roller-repair-powai': typeof WindowRollerRepairPowaiRoute
  '/window-track-repair-powai': typeof WindowTrackRepairPowaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluminium-door-installation-mumbai': typeof AluminiumDoorInstallationMumbaiRoute
  '/aluminium-kitchen-cupboard-mumbai': typeof AluminiumKitchenCupboardMumbaiRoute
  '/aluminium-partition-installation-mumbai': typeof AluminiumPartitionInstallationMumbaiRoute
  '/aluminium-partition-repair-mumbai': typeof AluminiumPartitionRepairMumbaiRoute
  '/aluminium-window-repair-powai': typeof AluminiumWindowRepairPowaiRoute
  '/bathroom-window-mumbai': typeof BathroomWindowMumbaiRoute
  '/custom-window-modification-mumbai': typeof CustomWindowModificationMumbaiRoute
  '/domal-window-repair-mumbai': typeof DomalWindowRepairMumbaiRoute
  '/french-windows-mumbai': typeof FrenchWindowsMumbaiRoute
  '/glass-balcony-railing-mumbai': typeof GlassBalconyRailingMumbaiRoute
  '/glass-partition-mumbai': typeof GlassPartitionMumbaiRoute
  '/glass-shop-powai': typeof GlassShopPowaiRoute
  '/invisible-grills-mumbai': typeof InvisibleGrillsMumbaiRoute
  '/mosquito-net-sliding-window-mumbai': typeof MosquitoNetSlidingWindowMumbaiRoute
  '/new-window-installation-mumbai': typeof NewWindowInstallationMumbaiRoute
  '/pigeon-net-installation-mumbai': typeof PigeonNetInstallationMumbaiRoute
  '/privacy': typeof PrivacyRoute
  '/rubber-gasket-sealing-mumbai': typeof RubberGasketSealingMumbaiRoute
  '/safety-nets-installation-mumbai': typeof SafetyNetsInstallationMumbaiRoute
  '/sliding-door-repair-powai': typeof SlidingDoorRepairPowaiRoute
  '/sliding-window-repair-powai': typeof SlidingWindowRepairPowaiRoute
  '/soundproof-window-upgrades-mumbai': typeof SoundproofWindowUpgradesMumbaiRoute
  '/terms': typeof TermsRoute
  '/window-alignment-maintenance-mumbai': typeof WindowAlignmentMaintenanceMumbaiRoute
  '/window-glass-replacement-powai': typeof WindowGlassReplacementPowaiRoute
  '/window-lock-repair-powai': typeof WindowLockRepairPowaiRoute
  '/window-repair-andheri-west-east': typeof WindowRepairAndheriWestEastRoute
  '/window-repair-bandra-juhu': typeof WindowRepairBandraJuhuRoute
  '/window-repair-bkc-kurla': typeof WindowRepairBkcKurlaRoute
  '/window-repair-chandivali-saki-vihar': typeof WindowRepairChandivaliSakiViharRoute
  '/window-repair-chembur-sion': typeof WindowRepairChemburSionRoute
  '/window-repair-colaba-fort': typeof WindowRepairColabaFortRoute
  '/window-repair-dadar-mahim': typeof WindowRepairDadarMahimRoute
  '/window-repair-goregaon-malad': typeof WindowRepairGoregaonMaladRoute
  '/window-repair-kandivali-borivali': typeof WindowRepairKandivaliBorivaliRoute
  '/window-repair-kanjurmarg-bhandup': typeof WindowRepairKanjurmargBhandupRoute
  '/window-repair-mulund-nahur': typeof WindowRepairMulundNahurRoute
  '/window-repair-mumbai': typeof WindowRepairMumbaiRoute
  '/window-repair-powai-hiranandani': typeof WindowRepairPowaiHiranandaniRoute
  '/window-repair-santacruz-khar': typeof WindowRepairSantacruzKharRoute
  '/window-repair-south-mumbai-cuffe-parade': typeof WindowRepairSouthMumbaiCuffeParadeRoute
  '/window-repair-thane': typeof WindowRepairThaneRoute
  '/window-repair-vikhroli-ghatkopar': typeof WindowRepairVikhroliGhatkoparRoute
  '/window-repair-worli-prabhadevi': typeof WindowRepairWorliPrabhadeviRoute
  '/window-roller-repair-powai': typeof WindowRollerRepairPowaiRoute
  '/window-track-repair-powai': typeof WindowTrackRepairPowaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluminium-door-installation-mumbai': typeof AluminiumDoorInstallationMumbaiRoute
  '/aluminium-kitchen-cupboard-mumbai': typeof AluminiumKitchenCupboardMumbaiRoute
  '/aluminium-partition-installation-mumbai': typeof AluminiumPartitionInstallationMumbaiRoute
  '/aluminium-partition-repair-mumbai': typeof AluminiumPartitionRepairMumbaiRoute
  '/aluminium-window-repair-powai': typeof AluminiumWindowRepairPowaiRoute
  '/bathroom-window-mumbai': typeof BathroomWindowMumbaiRoute
  '/custom-window-modification-mumbai': typeof CustomWindowModificationMumbaiRoute
  '/domal-window-repair-mumbai': typeof DomalWindowRepairMumbaiRoute
  '/french-windows-mumbai': typeof FrenchWindowsMumbaiRoute
  '/glass-balcony-railing-mumbai': typeof GlassBalconyRailingMumbaiRoute
  '/glass-partition-mumbai': typeof GlassPartitionMumbaiRoute
  '/glass-shop-powai': typeof GlassShopPowaiRoute
  '/invisible-grills-mumbai': typeof InvisibleGrillsMumbaiRoute
  '/mosquito-net-sliding-window-mumbai': typeof MosquitoNetSlidingWindowMumbaiRoute
  '/new-window-installation-mumbai': typeof NewWindowInstallationMumbaiRoute
  '/pigeon-net-installation-mumbai': typeof PigeonNetInstallationMumbaiRoute
  '/privacy': typeof PrivacyRoute
  '/rubber-gasket-sealing-mumbai': typeof RubberGasketSealingMumbaiRoute
  '/safety-nets-installation-mumbai': typeof SafetyNetsInstallationMumbaiRoute
  '/sliding-door-repair-powai': typeof SlidingDoorRepairPowaiRoute
  '/sliding-window-repair-powai': typeof SlidingWindowRepairPowaiRoute
  '/soundproof-window-upgrades-mumbai': typeof SoundproofWindowUpgradesMumbaiRoute
  '/terms': typeof TermsRoute
  '/window-alignment-maintenance-mumbai': typeof WindowAlignmentMaintenanceMumbaiRoute
  '/window-glass-replacement-powai': typeof WindowGlassReplacementPowaiRoute
  '/window-lock-repair-powai': typeof WindowLockRepairPowaiRoute
  '/window-repair-andheri-west-east': typeof WindowRepairAndheriWestEastRoute
  '/window-repair-bandra-juhu': typeof WindowRepairBandraJuhuRoute
  '/window-repair-bkc-kurla': typeof WindowRepairBkcKurlaRoute
  '/window-repair-chandivali-saki-vihar': typeof WindowRepairChandivaliSakiViharRoute
  '/window-repair-chembur-sion': typeof WindowRepairChemburSionRoute
  '/window-repair-colaba-fort': typeof WindowRepairColabaFortRoute
  '/window-repair-dadar-mahim': typeof WindowRepairDadarMahimRoute
  '/window-repair-goregaon-malad': typeof WindowRepairGoregaonMaladRoute
  '/window-repair-kandivali-borivali': typeof WindowRepairKandivaliBorivaliRoute
  '/window-repair-kanjurmarg-bhandup': typeof WindowRepairKanjurmargBhandupRoute
  '/window-repair-mulund-nahur': typeof WindowRepairMulundNahurRoute
  '/window-repair-mumbai': typeof WindowRepairMumbaiRoute
  '/window-repair-powai-hiranandani': typeof WindowRepairPowaiHiranandaniRoute
  '/window-repair-santacruz-khar': typeof WindowRepairSantacruzKharRoute
  '/window-repair-south-mumbai-cuffe-parade': typeof WindowRepairSouthMumbaiCuffeParadeRoute
  '/window-repair-thane': typeof WindowRepairThaneRoute
  '/window-repair-vikhroli-ghatkopar': typeof WindowRepairVikhroliGhatkoparRoute
  '/window-repair-worli-prabhadevi': typeof WindowRepairWorliPrabhadeviRoute
  '/window-roller-repair-powai': typeof WindowRollerRepairPowaiRoute
  '/window-track-repair-powai': typeof WindowTrackRepairPowaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluminium-door-installation-mumbai'
    | '/aluminium-kitchen-cupboard-mumbai'
    | '/aluminium-partition-installation-mumbai'
    | '/aluminium-partition-repair-mumbai'
    | '/aluminium-window-repair-powai'
    | '/bathroom-window-mumbai'
    | '/custom-window-modification-mumbai'
    | '/domal-window-repair-mumbai'
    | '/french-windows-mumbai'
    | '/glass-balcony-railing-mumbai'
    | '/glass-partition-mumbai'
    | '/glass-shop-powai'
    | '/invisible-grills-mumbai'
    | '/mosquito-net-sliding-window-mumbai'
    | '/new-window-installation-mumbai'
    | '/pigeon-net-installation-mumbai'
    | '/privacy'
    | '/rubber-gasket-sealing-mumbai'
    | '/safety-nets-installation-mumbai'
    | '/sliding-door-repair-powai'
    | '/sliding-window-repair-powai'
    | '/soundproof-window-upgrades-mumbai'
    | '/terms'
    | '/window-alignment-maintenance-mumbai'
    | '/window-glass-replacement-powai'
    | '/window-lock-repair-powai'
    | '/window-repair-andheri-west-east'
    | '/window-repair-bandra-juhu'
    | '/window-repair-bkc-kurla'
    | '/window-repair-chandivali-saki-vihar'
    | '/window-repair-chembur-sion'
    | '/window-repair-colaba-fort'
    | '/window-repair-dadar-mahim'
    | '/window-repair-goregaon-malad'
    | '/window-repair-kandivali-borivali'
    | '/window-repair-kanjurmarg-bhandup'
    | '/window-repair-mulund-nahur'
    | '/window-repair-mumbai'
    | '/window-repair-powai-hiranandani'
    | '/window-repair-santacruz-khar'
    | '/window-repair-south-mumbai-cuffe-parade'
    | '/window-repair-thane'
    | '/window-repair-vikhroli-ghatkopar'
    | '/window-repair-worli-prabhadevi'
    | '/window-roller-repair-powai'
    | '/window-track-repair-powai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluminium-door-installation-mumbai'
    | '/aluminium-kitchen-cupboard-mumbai'
    | '/aluminium-partition-installation-mumbai'
    | '/aluminium-partition-repair-mumbai'
    | '/aluminium-window-repair-powai'
    | '/bathroom-window-mumbai'
    | '/custom-window-modification-mumbai'
    | '/domal-window-repair-mumbai'
    | '/french-windows-mumbai'
    | '/glass-balcony-railing-mumbai'
    | '/glass-partition-mumbai'
    | '/glass-shop-powai'
    | '/invisible-grills-mumbai'
    | '/mosquito-net-sliding-window-mumbai'
    | '/new-window-installation-mumbai'
    | '/pigeon-net-installation-mumbai'
    | '/privacy'
    | '/rubber-gasket-sealing-mumbai'
    | '/safety-nets-installation-mumbai'
    | '/sliding-door-repair-powai'
    | '/sliding-window-repair-powai'
    | '/soundproof-window-upgrades-mumbai'
    | '/terms'
    | '/window-alignment-maintenance-mumbai'
    | '/window-glass-replacement-powai'
    | '/window-lock-repair-powai'
    | '/window-repair-andheri-west-east'
    | '/window-repair-bandra-juhu'
    | '/window-repair-bkc-kurla'
    | '/window-repair-chandivali-saki-vihar'
    | '/window-repair-chembur-sion'
    | '/window-repair-colaba-fort'
    | '/window-repair-dadar-mahim'
    | '/window-repair-goregaon-malad'
    | '/window-repair-kandivali-borivali'
    | '/window-repair-kanjurmarg-bhandup'
    | '/window-repair-mulund-nahur'
    | '/window-repair-mumbai'
    | '/window-repair-powai-hiranandani'
    | '/window-repair-santacruz-khar'
    | '/window-repair-south-mumbai-cuffe-parade'
    | '/window-repair-thane'
    | '/window-repair-vikhroli-ghatkopar'
    | '/window-repair-worli-prabhadevi'
    | '/window-roller-repair-powai'
    | '/window-track-repair-powai'
  id:
    | '__root__'
    | '/'
    | '/aluminium-door-installation-mumbai'
    | '/aluminium-kitchen-cupboard-mumbai'
    | '/aluminium-partition-installation-mumbai'
    | '/aluminium-partition-repair-mumbai'
    | '/aluminium-window-repair-powai'
    | '/bathroom-window-mumbai'
    | '/custom-window-modification-mumbai'
    | '/domal-window-repair-mumbai'
    | '/french-windows-mumbai'
    | '/glass-balcony-railing-mumbai'
    | '/glass-partition-mumbai'
    | '/glass-shop-powai'
    | '/invisible-grills-mumbai'
    | '/mosquito-net-sliding-window-mumbai'
    | '/new-window-installation-mumbai'
    | '/pigeon-net-installation-mumbai'
    | '/privacy'
    | '/rubber-gasket-sealing-mumbai'
    | '/safety-nets-installation-mumbai'
    | '/sliding-door-repair-powai'
    | '/sliding-window-repair-powai'
    | '/soundproof-window-upgrades-mumbai'
    | '/terms'
    | '/window-alignment-maintenance-mumbai'
    | '/window-glass-replacement-powai'
    | '/window-lock-repair-powai'
    | '/window-repair-andheri-west-east'
    | '/window-repair-bandra-juhu'
    | '/window-repair-bkc-kurla'
    | '/window-repair-chandivali-saki-vihar'
    | '/window-repair-chembur-sion'
    | '/window-repair-colaba-fort'
    | '/window-repair-dadar-mahim'
    | '/window-repair-goregaon-malad'
    | '/window-repair-kandivali-borivali'
    | '/window-repair-kanjurmarg-bhandup'
    | '/window-repair-mulund-nahur'
    | '/window-repair-mumbai'
    | '/window-repair-powai-hiranandani'
    | '/window-repair-santacruz-khar'
    | '/window-repair-south-mumbai-cuffe-parade'
    | '/window-repair-thane'
    | '/window-repair-vikhroli-ghatkopar'
    | '/window-repair-worli-prabhadevi'
    | '/window-roller-repair-powai'
    | '/window-track-repair-powai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AluminiumDoorInstallationMumbaiRoute: typeof AluminiumDoorInstallationMumbaiRoute
  AluminiumKitchenCupboardMumbaiRoute: typeof AluminiumKitchenCupboardMumbaiRoute
  AluminiumPartitionInstallationMumbaiRoute: typeof AluminiumPartitionInstallationMumbaiRoute
  AluminiumPartitionRepairMumbaiRoute: typeof AluminiumPartitionRepairMumbaiRoute
  AluminiumWindowRepairPowaiRoute: typeof AluminiumWindowRepairPowaiRoute
  BathroomWindowMumbaiRoute: typeof BathroomWindowMumbaiRoute
  CustomWindowModificationMumbaiRoute: typeof CustomWindowModificationMumbaiRoute
  DomalWindowRepairMumbaiRoute: typeof DomalWindowRepairMumbaiRoute
  FrenchWindowsMumbaiRoute: typeof FrenchWindowsMumbaiRoute
  GlassBalconyRailingMumbaiRoute: typeof GlassBalconyRailingMumbaiRoute
  GlassPartitionMumbaiRoute: typeof GlassPartitionMumbaiRoute
  GlassShopPowaiRoute: typeof GlassShopPowaiRoute
  InvisibleGrillsMumbaiRoute: typeof InvisibleGrillsMumbaiRoute
  MosquitoNetSlidingWindowMumbaiRoute: typeof MosquitoNetSlidingWindowMumbaiRoute
  NewWindowInstallationMumbaiRoute: typeof NewWindowInstallationMumbaiRoute
  PigeonNetInstallationMumbaiRoute: typeof PigeonNetInstallationMumbaiRoute
  PrivacyRoute: typeof PrivacyRoute
  RubberGasketSealingMumbaiRoute: typeof RubberGasketSealingMumbaiRoute
  SafetyNetsInstallationMumbaiRoute: typeof SafetyNetsInstallationMumbaiRoute
  SlidingDoorRepairPowaiRoute: typeof SlidingDoorRepairPowaiRoute
  SlidingWindowRepairPowaiRoute: typeof SlidingWindowRepairPowaiRoute
  SoundproofWindowUpgradesMumbaiRoute: typeof SoundproofWindowUpgradesMumbaiRoute
  TermsRoute: typeof TermsRoute
  WindowAlignmentMaintenanceMumbaiRoute: typeof WindowAlignmentMaintenanceMumbaiRoute
  WindowGlassReplacementPowaiRoute: typeof WindowGlassReplacementPowaiRoute
  WindowLockRepairPowaiRoute: typeof WindowLockRepairPowaiRoute
  WindowRepairAndheriWestEastRoute: typeof WindowRepairAndheriWestEastRoute
  WindowRepairBandraJuhuRoute: typeof WindowRepairBandraJuhuRoute
  WindowRepairBkcKurlaRoute: typeof WindowRepairBkcKurlaRoute
  WindowRepairChandivaliSakiViharRoute: typeof WindowRepairChandivaliSakiViharRoute
  WindowRepairChemburSionRoute: typeof WindowRepairChemburSionRoute
  WindowRepairColabaFortRoute: typeof WindowRepairColabaFortRoute
  WindowRepairDadarMahimRoute: typeof WindowRepairDadarMahimRoute
  WindowRepairGoregaonMaladRoute: typeof WindowRepairGoregaonMaladRoute
  WindowRepairKandivaliBorivaliRoute: typeof WindowRepairKandivaliBorivaliRoute
  WindowRepairKanjurmargBhandupRoute: typeof WindowRepairKanjurmargBhandupRoute
  WindowRepairMulundNahurRoute: typeof WindowRepairMulundNahurRoute
  WindowRepairMumbaiRoute: typeof WindowRepairMumbaiRoute
  WindowRepairPowaiHiranandaniRoute: typeof WindowRepairPowaiHiranandaniRoute
  WindowRepairSantacruzKharRoute: typeof WindowRepairSantacruzKharRoute
  WindowRepairSouthMumbaiCuffeParadeRoute: typeof WindowRepairSouthMumbaiCuffeParadeRoute
  WindowRepairThaneRoute: typeof WindowRepairThaneRoute
  WindowRepairVikhroliGhatkoparRoute: typeof WindowRepairVikhroliGhatkoparRoute
  WindowRepairWorliPrabhadeviRoute: typeof WindowRepairWorliPrabhadeviRoute
  WindowRollerRepairPowaiRoute: typeof WindowRollerRepairPowaiRoute
  WindowTrackRepairPowaiRoute: typeof WindowTrackRepairPowaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluminium-door-installation-mumbai': {
      id: '/aluminium-door-installation-mumbai'
      path: '/aluminium-door-installation-mumbai'
      fullPath: '/aluminium-door-installation-mumbai'
      preLoaderRoute: typeof AluminiumDoorInstallationMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluminium-kitchen-cupboard-mumbai': {
      id: '/aluminium-kitchen-cupboard-mumbai'
      path: '/aluminium-kitchen-cupboard-mumbai'
      fullPath: '/aluminium-kitchen-cupboard-mumbai'
      preLoaderRoute: typeof AluminiumKitchenCupboardMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluminium-partition-installation-mumbai': {
      id: '/aluminium-partition-installation-mumbai'
      path: '/aluminium-partition-installation-mumbai'
      fullPath: '/aluminium-partition-installation-mumbai'
      preLoaderRoute: typeof AluminiumPartitionInstallationMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluminium-partition-repair-mumbai': {
      id: '/aluminium-partition-repair-mumbai'
      path: '/aluminium-partition-repair-mumbai'
      fullPath: '/aluminium-partition-repair-mumbai'
      preLoaderRoute: typeof AluminiumPartitionRepairMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluminium-window-repair-powai': {
      id: '/aluminium-window-repair-powai'
      path: '/aluminium-window-repair-powai'
      fullPath: '/aluminium-window-repair-powai'
      preLoaderRoute: typeof AluminiumWindowRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-window-mumbai': {
      id: '/bathroom-window-mumbai'
      path: '/bathroom-window-mumbai'
      fullPath: '/bathroom-window-mumbai'
      preLoaderRoute: typeof BathroomWindowMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-window-modification-mumbai': {
      id: '/custom-window-modification-mumbai'
      path: '/custom-window-modification-mumbai'
      fullPath: '/custom-window-modification-mumbai'
      preLoaderRoute: typeof CustomWindowModificationMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domal-window-repair-mumbai': {
      id: '/domal-window-repair-mumbai'
      path: '/domal-window-repair-mumbai'
      fullPath: '/domal-window-repair-mumbai'
      preLoaderRoute: typeof DomalWindowRepairMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/french-windows-mumbai': {
      id: '/french-windows-mumbai'
      path: '/french-windows-mumbai'
      fullPath: '/french-windows-mumbai'
      preLoaderRoute: typeof FrenchWindowsMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass-balcony-railing-mumbai': {
      id: '/glass-balcony-railing-mumbai'
      path: '/glass-balcony-railing-mumbai'
      fullPath: '/glass-balcony-railing-mumbai'
      preLoaderRoute: typeof GlassBalconyRailingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass-partition-mumbai': {
      id: '/glass-partition-mumbai'
      path: '/glass-partition-mumbai'
      fullPath: '/glass-partition-mumbai'
      preLoaderRoute: typeof GlassPartitionMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass-shop-powai': {
      id: '/glass-shop-powai'
      path: '/glass-shop-powai'
      fullPath: '/glass-shop-powai'
      preLoaderRoute: typeof GlassShopPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisible-grills-mumbai': {
      id: '/invisible-grills-mumbai'
      path: '/invisible-grills-mumbai'
      fullPath: '/invisible-grills-mumbai'
      preLoaderRoute: typeof InvisibleGrillsMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosquito-net-sliding-window-mumbai': {
      id: '/mosquito-net-sliding-window-mumbai'
      path: '/mosquito-net-sliding-window-mumbai'
      fullPath: '/mosquito-net-sliding-window-mumbai'
      preLoaderRoute: typeof MosquitoNetSlidingWindowMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-window-installation-mumbai': {
      id: '/new-window-installation-mumbai'
      path: '/new-window-installation-mumbai'
      fullPath: '/new-window-installation-mumbai'
      preLoaderRoute: typeof NewWindowInstallationMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pigeon-net-installation-mumbai': {
      id: '/pigeon-net-installation-mumbai'
      path: '/pigeon-net-installation-mumbai'
      fullPath: '/pigeon-net-installation-mumbai'
      preLoaderRoute: typeof PigeonNetInstallationMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubber-gasket-sealing-mumbai': {
      id: '/rubber-gasket-sealing-mumbai'
      path: '/rubber-gasket-sealing-mumbai'
      fullPath: '/rubber-gasket-sealing-mumbai'
      preLoaderRoute: typeof RubberGasketSealingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-nets-installation-mumbai': {
      id: '/safety-nets-installation-mumbai'
      path: '/safety-nets-installation-mumbai'
      fullPath: '/safety-nets-installation-mumbai'
      preLoaderRoute: typeof SafetyNetsInstallationMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sliding-door-repair-powai': {
      id: '/sliding-door-repair-powai'
      path: '/sliding-door-repair-powai'
      fullPath: '/sliding-door-repair-powai'
      preLoaderRoute: typeof SlidingDoorRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sliding-window-repair-powai': {
      id: '/sliding-window-repair-powai'
      path: '/sliding-window-repair-powai'
      fullPath: '/sliding-window-repair-powai'
      preLoaderRoute: typeof SlidingWindowRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soundproof-window-upgrades-mumbai': {
      id: '/soundproof-window-upgrades-mumbai'
      path: '/soundproof-window-upgrades-mumbai'
      fullPath: '/soundproof-window-upgrades-mumbai'
      preLoaderRoute: typeof SoundproofWindowUpgradesMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-alignment-maintenance-mumbai': {
      id: '/window-alignment-maintenance-mumbai'
      path: '/window-alignment-maintenance-mumbai'
      fullPath: '/window-alignment-maintenance-mumbai'
      preLoaderRoute: typeof WindowAlignmentMaintenanceMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-glass-replacement-powai': {
      id: '/window-glass-replacement-powai'
      path: '/window-glass-replacement-powai'
      fullPath: '/window-glass-replacement-powai'
      preLoaderRoute: typeof WindowGlassReplacementPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-lock-repair-powai': {
      id: '/window-lock-repair-powai'
      path: '/window-lock-repair-powai'
      fullPath: '/window-lock-repair-powai'
      preLoaderRoute: typeof WindowLockRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-andheri-west-east': {
      id: '/window-repair-andheri-west-east'
      path: '/window-repair-andheri-west-east'
      fullPath: '/window-repair-andheri-west-east'
      preLoaderRoute: typeof WindowRepairAndheriWestEastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-bandra-juhu': {
      id: '/window-repair-bandra-juhu'
      path: '/window-repair-bandra-juhu'
      fullPath: '/window-repair-bandra-juhu'
      preLoaderRoute: typeof WindowRepairBandraJuhuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-bkc-kurla': {
      id: '/window-repair-bkc-kurla'
      path: '/window-repair-bkc-kurla'
      fullPath: '/window-repair-bkc-kurla'
      preLoaderRoute: typeof WindowRepairBkcKurlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-chandivali-saki-vihar': {
      id: '/window-repair-chandivali-saki-vihar'
      path: '/window-repair-chandivali-saki-vihar'
      fullPath: '/window-repair-chandivali-saki-vihar'
      preLoaderRoute: typeof WindowRepairChandivaliSakiViharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-chembur-sion': {
      id: '/window-repair-chembur-sion'
      path: '/window-repair-chembur-sion'
      fullPath: '/window-repair-chembur-sion'
      preLoaderRoute: typeof WindowRepairChemburSionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-colaba-fort': {
      id: '/window-repair-colaba-fort'
      path: '/window-repair-colaba-fort'
      fullPath: '/window-repair-colaba-fort'
      preLoaderRoute: typeof WindowRepairColabaFortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-dadar-mahim': {
      id: '/window-repair-dadar-mahim'
      path: '/window-repair-dadar-mahim'
      fullPath: '/window-repair-dadar-mahim'
      preLoaderRoute: typeof WindowRepairDadarMahimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-goregaon-malad': {
      id: '/window-repair-goregaon-malad'
      path: '/window-repair-goregaon-malad'
      fullPath: '/window-repair-goregaon-malad'
      preLoaderRoute: typeof WindowRepairGoregaonMaladRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-kandivali-borivali': {
      id: '/window-repair-kandivali-borivali'
      path: '/window-repair-kandivali-borivali'
      fullPath: '/window-repair-kandivali-borivali'
      preLoaderRoute: typeof WindowRepairKandivaliBorivaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-kanjurmarg-bhandup': {
      id: '/window-repair-kanjurmarg-bhandup'
      path: '/window-repair-kanjurmarg-bhandup'
      fullPath: '/window-repair-kanjurmarg-bhandup'
      preLoaderRoute: typeof WindowRepairKanjurmargBhandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-mulund-nahur': {
      id: '/window-repair-mulund-nahur'
      path: '/window-repair-mulund-nahur'
      fullPath: '/window-repair-mulund-nahur'
      preLoaderRoute: typeof WindowRepairMulundNahurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-mumbai': {
      id: '/window-repair-mumbai'
      path: '/window-repair-mumbai'
      fullPath: '/window-repair-mumbai'
      preLoaderRoute: typeof WindowRepairMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-powai-hiranandani': {
      id: '/window-repair-powai-hiranandani'
      path: '/window-repair-powai-hiranandani'
      fullPath: '/window-repair-powai-hiranandani'
      preLoaderRoute: typeof WindowRepairPowaiHiranandaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-santacruz-khar': {
      id: '/window-repair-santacruz-khar'
      path: '/window-repair-santacruz-khar'
      fullPath: '/window-repair-santacruz-khar'
      preLoaderRoute: typeof WindowRepairSantacruzKharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-south-mumbai-cuffe-parade': {
      id: '/window-repair-south-mumbai-cuffe-parade'
      path: '/window-repair-south-mumbai-cuffe-parade'
      fullPath: '/window-repair-south-mumbai-cuffe-parade'
      preLoaderRoute: typeof WindowRepairSouthMumbaiCuffeParadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-thane': {
      id: '/window-repair-thane'
      path: '/window-repair-thane'
      fullPath: '/window-repair-thane'
      preLoaderRoute: typeof WindowRepairThaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-vikhroli-ghatkopar': {
      id: '/window-repair-vikhroli-ghatkopar'
      path: '/window-repair-vikhroli-ghatkopar'
      fullPath: '/window-repair-vikhroli-ghatkopar'
      preLoaderRoute: typeof WindowRepairVikhroliGhatkoparRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-repair-worli-prabhadevi': {
      id: '/window-repair-worli-prabhadevi'
      path: '/window-repair-worli-prabhadevi'
      fullPath: '/window-repair-worli-prabhadevi'
      preLoaderRoute: typeof WindowRepairWorliPrabhadeviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-roller-repair-powai': {
      id: '/window-roller-repair-powai'
      path: '/window-roller-repair-powai'
      fullPath: '/window-roller-repair-powai'
      preLoaderRoute: typeof WindowRollerRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window-track-repair-powai': {
      id: '/window-track-repair-powai'
      path: '/window-track-repair-powai'
      fullPath: '/window-track-repair-powai'
      preLoaderRoute: typeof WindowTrackRepairPowaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AluminiumDoorInstallationMumbaiRoute: AluminiumDoorInstallationMumbaiRoute,
  AluminiumKitchenCupboardMumbaiRoute: AluminiumKitchenCupboardMumbaiRoute,
  AluminiumPartitionInstallationMumbaiRoute:
    AluminiumPartitionInstallationMumbaiRoute,
  AluminiumPartitionRepairMumbaiRoute: AluminiumPartitionRepairMumbaiRoute,
  AluminiumWindowRepairPowaiRoute: AluminiumWindowRepairPowaiRoute,
  BathroomWindowMumbaiRoute: BathroomWindowMumbaiRoute,
  CustomWindowModificationMumbaiRoute: CustomWindowModificationMumbaiRoute,
  DomalWindowRepairMumbaiRoute: DomalWindowRepairMumbaiRoute,
  FrenchWindowsMumbaiRoute: FrenchWindowsMumbaiRoute,
  GlassBalconyRailingMumbaiRoute: GlassBalconyRailingMumbaiRoute,
  GlassPartitionMumbaiRoute: GlassPartitionMumbaiRoute,
  GlassShopPowaiRoute: GlassShopPowaiRoute,
  InvisibleGrillsMumbaiRoute: InvisibleGrillsMumbaiRoute,
  MosquitoNetSlidingWindowMumbaiRoute: MosquitoNetSlidingWindowMumbaiRoute,
  NewWindowInstallationMumbaiRoute: NewWindowInstallationMumbaiRoute,
  PigeonNetInstallationMumbaiRoute: PigeonNetInstallationMumbaiRoute,
  PrivacyRoute: PrivacyRoute,
  RubberGasketSealingMumbaiRoute: RubberGasketSealingMumbaiRoute,
  SafetyNetsInstallationMumbaiRoute: SafetyNetsInstallationMumbaiRoute,
  SlidingDoorRepairPowaiRoute: SlidingDoorRepairPowaiRoute,
  SlidingWindowRepairPowaiRoute: SlidingWindowRepairPowaiRoute,
  SoundproofWindowUpgradesMumbaiRoute: SoundproofWindowUpgradesMumbaiRoute,
  TermsRoute: TermsRoute,
  WindowAlignmentMaintenanceMumbaiRoute: WindowAlignmentMaintenanceMumbaiRoute,
  WindowGlassReplacementPowaiRoute: WindowGlassReplacementPowaiRoute,
  WindowLockRepairPowaiRoute: WindowLockRepairPowaiRoute,
  WindowRepairAndheriWestEastRoute: WindowRepairAndheriWestEastRoute,
  WindowRepairBandraJuhuRoute: WindowRepairBandraJuhuRoute,
  WindowRepairBkcKurlaRoute: WindowRepairBkcKurlaRoute,
  WindowRepairChandivaliSakiViharRoute: WindowRepairChandivaliSakiViharRoute,
  WindowRepairChemburSionRoute: WindowRepairChemburSionRoute,
  WindowRepairColabaFortRoute: WindowRepairColabaFortRoute,
  WindowRepairDadarMahimRoute: WindowRepairDadarMahimRoute,
  WindowRepairGoregaonMaladRoute: WindowRepairGoregaonMaladRoute,
  WindowRepairKandivaliBorivaliRoute: WindowRepairKandivaliBorivaliRoute,
  WindowRepairKanjurmargBhandupRoute: WindowRepairKanjurmargBhandupRoute,
  WindowRepairMulundNahurRoute: WindowRepairMulundNahurRoute,
  WindowRepairMumbaiRoute: WindowRepairMumbaiRoute,
  WindowRepairPowaiHiranandaniRoute: WindowRepairPowaiHiranandaniRoute,
  WindowRepairSantacruzKharRoute: WindowRepairSantacruzKharRoute,
  WindowRepairSouthMumbaiCuffeParadeRoute:
    WindowRepairSouthMumbaiCuffeParadeRoute,
  WindowRepairThaneRoute: WindowRepairThaneRoute,
  WindowRepairVikhroliGhatkoparRoute: WindowRepairVikhroliGhatkoparRoute,
  WindowRepairWorliPrabhadeviRoute: WindowRepairWorliPrabhadeviRoute,
  WindowRollerRepairPowaiRoute: WindowRollerRepairPowaiRoute,
  WindowTrackRepairPowaiRoute: WindowTrackRepairPowaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
